//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ContactList
{
	private List<Contact> _contacts
	{
		get;
		set;
	}

	public virtual Contact Contact
	{
		get;
		set;
	}

	public virtual List<Contact> GenerateContacts()
	{
		throw new System.NotImplementedException();
	}

	public virtual Contact GetContact(int location)
	{
		throw new System.NotImplementedException();
	}

}

