//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ConversationList
{
	private List<Conversation> _conversations
	{
		get;
		set;
	}

	public virtual IEnumerable<Conversation> Conversation
	{
		get;
		set;
	}

	public virtual List<Conversation> GenerateConversations()
	{
		throw new System.NotImplementedException();
	}

	public virtual Conversation AccessConversation(int location)
	{
		throw new System.NotImplementedException();
	}

	public virtual void AddNewConversation(Contact contact)
	{
		throw new System.NotImplementedException();
	}

}

