//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Conversation
{
	private List<Message> _messages
	{
		get;
		set;
	}

	private Contact _who
	{
		get;
		set;
	}

	private object _phoneNumber
	{
		get;
		set;
	}

	public virtual Contact Contact
	{
		get;
		set;
	}

	public virtual IEnumerable<Message> Message
	{
		get;
		set;
	}

	public virtual void AddMessage(Message message)
	{
		throw new System.NotImplementedException();
	}

	public virtual void DeleteMessage(Int location)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetMessage(int location)
	{
		throw new System.NotImplementedException();
	}

}

