//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public class Message
{
	private string _text
	{
		get;
		set;
	}

	private Stream _multi
	{
		get;
		set;
	}

	private string _phoneNumber
	{
		get;
		set;
	}

	private bool _isMMS
	{
		get;
		set;
	}

}

